[[themes]]
name = "termcolors"
[themes.palette]
background = "#1e1e2e" # base
foreground = "#cdd6f4" # text
selection_background = "#585b70" # surface2
selection_foreground = "#cdd6f4" # text
black = "#45475a" # surface1
bright_black = "#585b70" # surface2
red = "#f38ba8" # red
bright_red = "#f38ba8" # red
green = "#a6e3a1"
bright_green = "#a6e3a1"
yellow = "#f9e2af"
bright_yellow = "#f9e2af"
blue = "#89b4fa"
bright_blue = "#89b4fa"
magenta = "#cba6f7" # mauve
bright_magenta = "#cba6f7" # mauve
cyan = "#94e2d5" # teal
bright_cyan = "#94e2d5" # teal
white = "#bac2de" # subtext1
bright_white = "#a6adc8" # subtext0
# $rosewater = "#f5e0dc"
# $flamingo = "#f2cdcd"
# $pink = "#f5c2e7"
# $mauve = "#cba6f7"
# $maroon = "#eba0ac"
# $peach = "#fab387"
# $teal = "#94e2d5"
# $sky = "#89dceb"
# $sapphire = "#74c7ec"
# $lavender = "#b4befe"
# $text = "#cdd6f4"
# $subtext1 = "#bac2de"
# $subtext0 = "#a6adc8"
# $overlay2 = "#9399b2"
# $overlay1 = "#7f849c"
# $overlay0 = "#6c7086"
# $surface2 = "#585b70"
# $surface1 = "#45475a"
# $surface0 = "#313244"
# $base = "#1e1e2e"
# $mantle = "#181825"
# $crust = "#11111b"
[themes.component_style]
block_title = { fg = "Blue"  }
playback_track = { fg = "Magenta", modifiers = ["Bold"] }
playback_album = { fg = "Yellow" }
playback_metadata = { fg = "Black" }
playback_progress_bar = { bg = "Black", fg = "Magenta" }
current_playing = { fg = "Magenta", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
