#!/usr/bin/env bash

bspc config border_width    2
bspc config window_gap      12

edges=(top bottom left right)
for d in ${edges[@]}; do
    bspc config "${d}_padding" -6
done

bspc config split_ratio     0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

if command -v sxhkd &>/dev/null; then
    export SXHKD_SHELL=/bin/sh
    killall -q sxhkd
    sxhkd &
fi

if command -v picom &>/dev/null; then
    killall -q picom
    picom 2>&1 &
fi

killall -q polybar
primary=$(bspc query -M -m primary --names)
for monitor in $(bspc query -M --names); do
    bspc monitor "$monitor" -d 1 2 3 4 5 6 7 8 9 10

    if command -v polybar &>/dev/null; then
        export POLYBAR_MONITOR="$monitor"

        if [ "$monitor" = "$primary" ]; then
            polybar -r main 2>&1 &
        else
            polybar -r secondary 2>&1 &
        fi
    fi
done
