#!/usr/bin/env zsh
# Open a terminator window with vim in it
# Pass command line arguments to vim
function vimterm()
{
  terminator -b --layout=vimterm -e "${HOME}/scripts/term solarized light vim $@" &> /dev/null & disown
}
